package com.ari.mybatis.dao;

import com.ari.mybatis.bean.Agmachinery;

public interface AgmachineryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table agmachinery
     *
     * @mbggenerated Sun Jun 06 14:27:50 CST 2021
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table agmachinery
     *
     * @mbggenerated Sun Jun 06 14:27:50 CST 2021
     */
    int insert(Agmachinery record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table agmachinery
     *
     * @mbggenerated Sun Jun 06 14:27:50 CST 2021
     */
    int insertSelective(Agmachinery record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table agmachinery
     *
     * @mbggenerated Sun Jun 06 14:27:50 CST 2021
     */
    Agmachinery selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table agmachinery
     *
     * @mbggenerated Sun Jun 06 14:27:50 CST 2021
     */
    int updateByPrimaryKeySelective(Agmachinery record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table agmachinery
     *
     * @mbggenerated Sun Jun 06 14:27:50 CST 2021
     */
    int updateByPrimaryKey(Agmachinery record);
}