package com.ari.mybatis.dao;

import com.ari.mybatis.bean.agriculturetype;

public interface agriculturetypeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table agriculturetype
     *
     * @mbggenerated Sun Jun 06 14:27:50 CST 2021
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table agriculturetype
     *
     * @mbggenerated Sun Jun 06 14:27:50 CST 2021
     */
    int insert(agriculturetype record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table agriculturetype
     *
     * @mbggenerated Sun Jun 06 14:27:50 CST 2021
     */
    int insertSelective(agriculturetype record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table agriculturetype
     *
     * @mbggenerated Sun Jun 06 14:27:50 CST 2021
     */
    agriculturetype selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table agriculturetype
     *
     * @mbggenerated Sun Jun 06 14:27:50 CST 2021
     */
    int updateByPrimaryKeySelective(agriculturetype record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table agriculturetype
     *
     * @mbggenerated Sun Jun 06 14:27:50 CST 2021
     */
    int updateByPrimaryKey(agriculturetype record);
}