package com.ari.mybatis.dao;

import com.ari.mybatis.bean.Good;

public interface GoodMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table good
     *
     * @mbggenerated Sun Jun 06 14:27:50 CST 2021
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table good
     *
     * @mbggenerated Sun Jun 06 14:27:50 CST 2021
     */
    int insert(Good record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table good
     *
     * @mbggenerated Sun Jun 06 14:27:50 CST 2021
     */
    int insertSelective(Good record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table good
     *
     * @mbggenerated Sun Jun 06 14:27:50 CST 2021
     */
    Good selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table good
     *
     * @mbggenerated Sun Jun 06 14:27:50 CST 2021
     */
    int updateByPrimaryKeySelective(Good record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table good
     *
     * @mbggenerated Sun Jun 06 14:27:50 CST 2021
     */
    int updateByPrimaryKey(Good record);
}