package com.ari.mybatis.dao;

import com.ari.mybatis.bean.Plot;

public interface PlotMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table plot
     *
     * @mbggenerated Sun Jun 06 14:27:50 CST 2021
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table plot
     *
     * @mbggenerated Sun Jun 06 14:27:50 CST 2021
     */
    int insert(Plot record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table plot
     *
     * @mbggenerated Sun Jun 06 14:27:50 CST 2021
     */
    int insertSelective(Plot record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table plot
     *
     * @mbggenerated Sun Jun 06 14:27:50 CST 2021
     */
    Plot selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table plot
     *
     * @mbggenerated Sun Jun 06 14:27:50 CST 2021
     */
    int updateByPrimaryKeySelective(Plot record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table plot
     *
     * @mbggenerated Sun Jun 06 14:27:50 CST 2021
     */
    int updateByPrimaryKey(Plot record);
}