package com.ari.mybatis.dao;

import com.ari.mybatis.bean.UserInfo;

public interface UserInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userinfo
     *
     * @mbggenerated Sun Jun 06 14:27:50 CST 2021
     */
    int deleteByPrimaryKey(Integer userid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userinfo
     *
     * @mbggenerated Sun Jun 06 14:27:50 CST 2021
     */
    int insert(UserInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userinfo
     *
     * @mbggenerated Sun Jun 06 14:27:50 CST 2021
     */
    int insertSelective(UserInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userinfo
     *
     * @mbggenerated Sun Jun 06 14:27:50 CST 2021
     */
    UserInfo selectByPrimaryKey(Integer userid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userinfo
     *
     * @mbggenerated Sun Jun 06 14:27:50 CST 2021
     */
    int updateByPrimaryKeySelective(UserInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userinfo
     *
     * @mbggenerated Sun Jun 06 14:27:50 CST 2021
     */
    int updateByPrimaryKey(UserInfo record);

	UserInfo login(String useraccount, String userpassword);
}