package com.ari.mybatis.dao;

import com.ari.mybatis.bean.wuliu;

public interface wuliuMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wuliuxinxi
     *
     * @mbggenerated Sun Jun 06 14:27:50 CST 2021
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wuliuxinxi
     *
     * @mbggenerated Sun Jun 06 14:27:50 CST 2021
     */
    int insert(wuliu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wuliuxinxi
     *
     * @mbggenerated Sun Jun 06 14:27:50 CST 2021
     */
    int insertSelective(wuliu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wuliuxinxi
     *
     * @mbggenerated Sun Jun 06 14:27:50 CST 2021
     */
    wuliu selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wuliuxinxi
     *
     * @mbggenerated Sun Jun 06 14:27:50 CST 2021
     */
    int updateByPrimaryKeySelective(wuliu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wuliuxinxi
     *
     * @mbggenerated Sun Jun 06 14:27:50 CST 2021
     */
    int updateByPrimaryKey(wuliu record);
}