package com.ari.mybatis.bean;

public class Agmachinery {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column agmachinery.id
     *
     * @mbggenerated Sun Jun 06 14:27:50 CST 2021
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column agmachinery.type
     *
     * @mbggenerated Sun Jun 06 14:27:50 CST 2021
     */
    private String type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column agmachinery.name
     *
     * @mbggenerated Sun Jun 06 14:27:50 CST 2021
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column agmachinery.model
     *
     * @mbggenerated Sun Jun 06 14:27:50 CST 2021
     */
    private String model;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column agmachinery.people
     *
     * @mbggenerated Sun Jun 06 14:27:50 CST 2021
     */
    private String people;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column agmachinery.date
     *
     * @mbggenerated Sun Jun 06 14:27:50 CST 2021
     */
    private String date;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column agmachinery.img
     *
     * @mbggenerated Sun Jun 06 14:27:50 CST 2021
     */
    private String img;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column agmachinery.id
     *
     * @return the value of agmachinery.id
     *
     * @mbggenerated Sun Jun 06 14:27:50 CST 2021
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column agmachinery.id
     *
     * @param id the value for agmachinery.id
     *
     * @mbggenerated Sun Jun 06 14:27:50 CST 2021
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column agmachinery.type
     *
     * @return the value of agmachinery.type
     *
     * @mbggenerated Sun Jun 06 14:27:50 CST 2021
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column agmachinery.type
     *
     * @param type the value for agmachinery.type
     *
     * @mbggenerated Sun Jun 06 14:27:50 CST 2021
     */
    public void setType(String type) {
        this.type = type == null ? null : type.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column agmachinery.name
     *
     * @return the value of agmachinery.name
     *
     * @mbggenerated Sun Jun 06 14:27:50 CST 2021
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column agmachinery.name
     *
     * @param name the value for agmachinery.name
     *
     * @mbggenerated Sun Jun 06 14:27:50 CST 2021
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column agmachinery.model
     *
     * @return the value of agmachinery.model
     *
     * @mbggenerated Sun Jun 06 14:27:50 CST 2021
     */
    public String getModel() {
        return model;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column agmachinery.model
     *
     * @param model the value for agmachinery.model
     *
     * @mbggenerated Sun Jun 06 14:27:50 CST 2021
     */
    public void setModel(String model) {
        this.model = model == null ? null : model.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column agmachinery.people
     *
     * @return the value of agmachinery.people
     *
     * @mbggenerated Sun Jun 06 14:27:50 CST 2021
     */
    public String getPeople() {
        return people;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column agmachinery.people
     *
     * @param people the value for agmachinery.people
     *
     * @mbggenerated Sun Jun 06 14:27:50 CST 2021
     */
    public void setPeople(String people) {
        this.people = people == null ? null : people.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column agmachinery.date
     *
     * @return the value of agmachinery.date
     *
     * @mbggenerated Sun Jun 06 14:27:50 CST 2021
     */
    public String getDate() {
        return date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column agmachinery.date
     *
     * @param date the value for agmachinery.date
     *
     * @mbggenerated Sun Jun 06 14:27:50 CST 2021
     */
    public void setDate(String date) {
        this.date = date == null ? null : date.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column agmachinery.img
     *
     * @return the value of agmachinery.img
     *
     * @mbggenerated Sun Jun 06 14:27:50 CST 2021
     */
    public String getImg() {
        return img;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column agmachinery.img
     *
     * @param img the value for agmachinery.img
     *
     * @mbggenerated Sun Jun 06 14:27:50 CST 2021
     */
    public void setImg(String img) {
        this.img = img == null ? null : img.trim();
    }
}