package com.ari.mybatis.bean;

public class agriculturetype {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column agriculturetype.id
     *
     * @mbggenerated Sun Jun 06 14:27:50 CST 2021
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column agriculturetype.name
     *
     * @mbggenerated Sun Jun 06 14:27:50 CST 2021
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column agriculturetype.permuyield
     *
     * @mbggenerated Sun Jun 06 14:27:50 CST 2021
     */
    private String permuyield;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column agriculturetype.massif
     *
     * @mbggenerated Sun Jun 06 14:27:50 CST 2021
     */
    private String massif;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column agriculturetype.cycle
     *
     * @mbggenerated Sun Jun 06 14:27:50 CST 2021
     */
    private String cycle;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column agriculturetype.smonth
     *
     * @mbggenerated Sun Jun 06 14:27:50 CST 2021
     */
    private String smonth;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column agriculturetype.emonth
     *
     * @mbggenerated Sun Jun 06 14:27:50 CST 2021
     */
    private String emonth;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column agriculturetype.describe11
     *
     * @mbggenerated Sun Jun 06 14:27:50 CST 2021
     */
    private String describe11;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column agriculturetype.id
     *
     * @return the value of agriculturetype.id
     *
     * @mbggenerated Sun Jun 06 14:27:50 CST 2021
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column agriculturetype.id
     *
     * @param id the value for agriculturetype.id
     *
     * @mbggenerated Sun Jun 06 14:27:50 CST 2021
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column agriculturetype.name
     *
     * @return the value of agriculturetype.name
     *
     * @mbggenerated Sun Jun 06 14:27:50 CST 2021
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column agriculturetype.name
     *
     * @param name the value for agriculturetype.name
     *
     * @mbggenerated Sun Jun 06 14:27:50 CST 2021
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column agriculturetype.permuyield
     *
     * @return the value of agriculturetype.permuyield
     *
     * @mbggenerated Sun Jun 06 14:27:50 CST 2021
     */
    public String getPermuyield() {
        return permuyield;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column agriculturetype.permuyield
     *
     * @param permuyield the value for agriculturetype.permuyield
     *
     * @mbggenerated Sun Jun 06 14:27:50 CST 2021
     */
    public void setPermuyield(String permuyield) {
        this.permuyield = permuyield == null ? null : permuyield.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column agriculturetype.massif
     *
     * @return the value of agriculturetype.massif
     *
     * @mbggenerated Sun Jun 06 14:27:50 CST 2021
     */
    public String getMassif() {
        return massif;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column agriculturetype.massif
     *
     * @param massif the value for agriculturetype.massif
     *
     * @mbggenerated Sun Jun 06 14:27:50 CST 2021
     */
    public void setMassif(String massif) {
        this.massif = massif == null ? null : massif.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column agriculturetype.cycle
     *
     * @return the value of agriculturetype.cycle
     *
     * @mbggenerated Sun Jun 06 14:27:50 CST 2021
     */
    public String getCycle() {
        return cycle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column agriculturetype.cycle
     *
     * @param cycle the value for agriculturetype.cycle
     *
     * @mbggenerated Sun Jun 06 14:27:50 CST 2021
     */
    public void setCycle(String cycle) {
        this.cycle = cycle == null ? null : cycle.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column agriculturetype.smonth
     *
     * @return the value of agriculturetype.smonth
     *
     * @mbggenerated Sun Jun 06 14:27:50 CST 2021
     */
    public String getSmonth() {
        return smonth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column agriculturetype.smonth
     *
     * @param smonth the value for agriculturetype.smonth
     *
     * @mbggenerated Sun Jun 06 14:27:50 CST 2021
     */
    public void setSmonth(String smonth) {
        this.smonth = smonth == null ? null : smonth.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column agriculturetype.emonth
     *
     * @return the value of agriculturetype.emonth
     *
     * @mbggenerated Sun Jun 06 14:27:50 CST 2021
     */
    public String getEmonth() {
        return emonth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column agriculturetype.emonth
     *
     * @param emonth the value for agriculturetype.emonth
     *
     * @mbggenerated Sun Jun 06 14:27:50 CST 2021
     */
    public void setEmonth(String emonth) {
        this.emonth = emonth == null ? null : emonth.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column agriculturetype.describe11
     *
     * @return the value of agriculturetype.describe11
     *
     * @mbggenerated Sun Jun 06 14:27:50 CST 2021
     */
    public String getDescribe11() {
        return describe11;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column agriculturetype.describe11
     *
     * @param describe11 the value for agriculturetype.describe11
     *
     * @mbggenerated Sun Jun 06 14:27:50 CST 2021
     */
    public void setDescribe11(String describe11) {
        this.describe11 = describe11 == null ? null : describe11.trim();
    }
}