package com.ari.mybatis.bean;

public class Company {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column company.id
     *
     * @mbggenerated Sun Jun 06 14:27:50 CST 2021
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column company.name
     *
     * @mbggenerated Sun Jun 06 14:27:50 CST 2021
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column company.introduce
     *
     * @mbggenerated Sun Jun 06 14:27:50 CST 2021
     */
    private String introduce;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column company.img
     *
     * @mbggenerated Sun Jun 06 14:27:50 CST 2021
     */
    private String img;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column company.sina
     *
     * @mbggenerated Sun Jun 06 14:27:50 CST 2021
     */
    private String sina;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column company.tencent
     *
     * @mbggenerated Sun Jun 06 14:27:50 CST 2021
     */
    private String tencent;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column company.site
     *
     * @mbggenerated Sun Jun 06 14:27:50 CST 2021
     */
    private String site;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column company.email
     *
     * @mbggenerated Sun Jun 06 14:27:50 CST 2021
     */
    private String email;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column company.phone
     *
     * @mbggenerated Sun Jun 06 14:27:50 CST 2021
     */
    private String phone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column company.linkman
     *
     * @mbggenerated Sun Jun 06 14:27:50 CST 2021
     */
    private String linkman;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column company.id
     *
     * @return the value of company.id
     *
     * @mbggenerated Sun Jun 06 14:27:50 CST 2021
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column company.id
     *
     * @param id the value for company.id
     *
     * @mbggenerated Sun Jun 06 14:27:50 CST 2021
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column company.name
     *
     * @return the value of company.name
     *
     * @mbggenerated Sun Jun 06 14:27:50 CST 2021
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column company.name
     *
     * @param name the value for company.name
     *
     * @mbggenerated Sun Jun 06 14:27:50 CST 2021
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column company.introduce
     *
     * @return the value of company.introduce
     *
     * @mbggenerated Sun Jun 06 14:27:50 CST 2021
     */
    public String getIntroduce() {
        return introduce;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column company.introduce
     *
     * @param introduce the value for company.introduce
     *
     * @mbggenerated Sun Jun 06 14:27:50 CST 2021
     */
    public void setIntroduce(String introduce) {
        this.introduce = introduce == null ? null : introduce.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column company.img
     *
     * @return the value of company.img
     *
     * @mbggenerated Sun Jun 06 14:27:50 CST 2021
     */
    public String getImg() {
        return img;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column company.img
     *
     * @param img the value for company.img
     *
     * @mbggenerated Sun Jun 06 14:27:50 CST 2021
     */
    public void setImg(String img) {
        this.img = img == null ? null : img.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column company.sina
     *
     * @return the value of company.sina
     *
     * @mbggenerated Sun Jun 06 14:27:50 CST 2021
     */
    public String getSina() {
        return sina;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column company.sina
     *
     * @param sina the value for company.sina
     *
     * @mbggenerated Sun Jun 06 14:27:50 CST 2021
     */
    public void setSina(String sina) {
        this.sina = sina == null ? null : sina.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column company.tencent
     *
     * @return the value of company.tencent
     *
     * @mbggenerated Sun Jun 06 14:27:50 CST 2021
     */
    public String getTencent() {
        return tencent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column company.tencent
     *
     * @param tencent the value for company.tencent
     *
     * @mbggenerated Sun Jun 06 14:27:50 CST 2021
     */
    public void setTencent(String tencent) {
        this.tencent = tencent == null ? null : tencent.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column company.site
     *
     * @return the value of company.site
     *
     * @mbggenerated Sun Jun 06 14:27:50 CST 2021
     */
    public String getSite() {
        return site;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column company.site
     *
     * @param site the value for company.site
     *
     * @mbggenerated Sun Jun 06 14:27:50 CST 2021
     */
    public void setSite(String site) {
        this.site = site == null ? null : site.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column company.email
     *
     * @return the value of company.email
     *
     * @mbggenerated Sun Jun 06 14:27:50 CST 2021
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column company.email
     *
     * @param email the value for company.email
     *
     * @mbggenerated Sun Jun 06 14:27:50 CST 2021
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column company.phone
     *
     * @return the value of company.phone
     *
     * @mbggenerated Sun Jun 06 14:27:50 CST 2021
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column company.phone
     *
     * @param phone the value for company.phone
     *
     * @mbggenerated Sun Jun 06 14:27:50 CST 2021
     */
    public void setPhone(String phone) {
        this.phone = phone == null ? null : phone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column company.linkman
     *
     * @return the value of company.linkman
     *
     * @mbggenerated Sun Jun 06 14:27:50 CST 2021
     */
    public String getLinkman() {
        return linkman;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column company.linkman
     *
     * @param linkman the value for company.linkman
     *
     * @mbggenerated Sun Jun 06 14:27:50 CST 2021
     */
    public void setLinkman(String linkman) {
        this.linkman = linkman == null ? null : linkman.trim();
    }
}