package com.ari.mybatis.bean;

public class Employee {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employee.id
     *
     * @mbggenerated Sun Jun 06 14:27:50 CST 2021
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employee.identitcard
     *
     * @mbggenerated Sun Jun 06 14:27:50 CST 2021
     */
    private String identitcard;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employee.date
     *
     * @mbggenerated Sun Jun 06 14:27:50 CST 2021
     */
    private String date;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employee.birthday
     *
     * @mbggenerated Sun Jun 06 14:27:50 CST 2021
     */
    private String birthday;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employee.permisson
     *
     * @mbggenerated Sun Jun 06 14:27:50 CST 2021
     */
    private String permisson;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employee.gendy
     *
     * @mbggenerated Sun Jun 06 14:27:50 CST 2021
     */
    private String gendy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employee.homesite
     *
     * @mbggenerated Sun Jun 06 14:27:50 CST 2021
     */
    private String homesite;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employee.phone
     *
     * @mbggenerated Sun Jun 06 14:27:50 CST 2021
     */
    private String phone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employee.cardnumber
     *
     * @mbggenerated Sun Jun 06 14:27:50 CST 2021
     */
    private String cardnumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employee.img
     *
     * @mbggenerated Sun Jun 06 14:27:50 CST 2021
     */
    private String img;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employee.remark
     *
     * @mbggenerated Sun Jun 06 14:27:50 CST 2021
     */
    private String remark;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employee.id
     *
     * @return the value of employee.id
     *
     * @mbggenerated Sun Jun 06 14:27:50 CST 2021
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employee.id
     *
     * @param id the value for employee.id
     *
     * @mbggenerated Sun Jun 06 14:27:50 CST 2021
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employee.identitcard
     *
     * @return the value of employee.identitcard
     *
     * @mbggenerated Sun Jun 06 14:27:50 CST 2021
     */
    public String getIdentitcard() {
        return identitcard;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employee.identitcard
     *
     * @param identitcard the value for employee.identitcard
     *
     * @mbggenerated Sun Jun 06 14:27:50 CST 2021
     */
    public void setIdentitcard(String identitcard) {
        this.identitcard = identitcard == null ? null : identitcard.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employee.date
     *
     * @return the value of employee.date
     *
     * @mbggenerated Sun Jun 06 14:27:50 CST 2021
     */
    public String getDate() {
        return date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employee.date
     *
     * @param date the value for employee.date
     *
     * @mbggenerated Sun Jun 06 14:27:50 CST 2021
     */
    public void setDate(String date) {
        this.date = date == null ? null : date.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employee.birthday
     *
     * @return the value of employee.birthday
     *
     * @mbggenerated Sun Jun 06 14:27:50 CST 2021
     */
    public String getBirthday() {
        return birthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employee.birthday
     *
     * @param birthday the value for employee.birthday
     *
     * @mbggenerated Sun Jun 06 14:27:50 CST 2021
     */
    public void setBirthday(String birthday) {
        this.birthday = birthday == null ? null : birthday.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employee.permisson
     *
     * @return the value of employee.permisson
     *
     * @mbggenerated Sun Jun 06 14:27:50 CST 2021
     */
    public String getPermisson() {
        return permisson;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employee.permisson
     *
     * @param permisson the value for employee.permisson
     *
     * @mbggenerated Sun Jun 06 14:27:50 CST 2021
     */
    public void setPermisson(String permisson) {
        this.permisson = permisson == null ? null : permisson.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employee.gendy
     *
     * @return the value of employee.gendy
     *
     * @mbggenerated Sun Jun 06 14:27:50 CST 2021
     */
    public String getGendy() {
        return gendy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employee.gendy
     *
     * @param gendy the value for employee.gendy
     *
     * @mbggenerated Sun Jun 06 14:27:50 CST 2021
     */
    public void setGendy(String gendy) {
        this.gendy = gendy == null ? null : gendy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employee.homesite
     *
     * @return the value of employee.homesite
     *
     * @mbggenerated Sun Jun 06 14:27:50 CST 2021
     */
    public String getHomesite() {
        return homesite;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employee.homesite
     *
     * @param homesite the value for employee.homesite
     *
     * @mbggenerated Sun Jun 06 14:27:50 CST 2021
     */
    public void setHomesite(String homesite) {
        this.homesite = homesite == null ? null : homesite.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employee.phone
     *
     * @return the value of employee.phone
     *
     * @mbggenerated Sun Jun 06 14:27:50 CST 2021
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employee.phone
     *
     * @param phone the value for employee.phone
     *
     * @mbggenerated Sun Jun 06 14:27:50 CST 2021
     */
    public void setPhone(String phone) {
        this.phone = phone == null ? null : phone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employee.cardnumber
     *
     * @return the value of employee.cardnumber
     *
     * @mbggenerated Sun Jun 06 14:27:50 CST 2021
     */
    public String getCardnumber() {
        return cardnumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employee.cardnumber
     *
     * @param cardnumber the value for employee.cardnumber
     *
     * @mbggenerated Sun Jun 06 14:27:50 CST 2021
     */
    public void setCardnumber(String cardnumber) {
        this.cardnumber = cardnumber == null ? null : cardnumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employee.img
     *
     * @return the value of employee.img
     *
     * @mbggenerated Sun Jun 06 14:27:50 CST 2021
     */
    public String getImg() {
        return img;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employee.img
     *
     * @param img the value for employee.img
     *
     * @mbggenerated Sun Jun 06 14:27:50 CST 2021
     */
    public void setImg(String img) {
        this.img = img == null ? null : img.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employee.remark
     *
     * @return the value of employee.remark
     *
     * @mbggenerated Sun Jun 06 14:27:50 CST 2021
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employee.remark
     *
     * @param remark the value for employee.remark
     *
     * @mbggenerated Sun Jun 06 14:27:50 CST 2021
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }
}