package com.ari.mybatis.bean;

public class Equipment {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column equipment.id
     *
     * @mbggenerated Sun Jun 06 14:27:50 CST 2021
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column equipment.number
     *
     * @mbggenerated Sun Jun 06 14:27:50 CST 2021
     */
    private String number;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column equipment.name
     *
     * @mbggenerated Sun Jun 06 14:27:50 CST 2021
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column equipment.statue
     *
     * @mbggenerated Sun Jun 06 14:27:50 CST 2021
     */
    private String statue;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column equipment.building
     *
     * @mbggenerated Sun Jun 06 14:27:50 CST 2021
     */
    private String building;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column equipment.principal
     *
     * @mbggenerated Sun Jun 06 14:27:50 CST 2021
     */
    private String principal;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column equipment.remrk
     *
     * @mbggenerated Sun Jun 06 14:27:50 CST 2021
     */
    private String remrk;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column equipment.id
     *
     * @return the value of equipment.id
     *
     * @mbggenerated Sun Jun 06 14:27:50 CST 2021
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column equipment.id
     *
     * @param id the value for equipment.id
     *
     * @mbggenerated Sun Jun 06 14:27:50 CST 2021
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column equipment.number
     *
     * @return the value of equipment.number
     *
     * @mbggenerated Sun Jun 06 14:27:50 CST 2021
     */
    public String getNumber() {
        return number;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column equipment.number
     *
     * @param number the value for equipment.number
     *
     * @mbggenerated Sun Jun 06 14:27:50 CST 2021
     */
    public void setNumber(String number) {
        this.number = number == null ? null : number.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column equipment.name
     *
     * @return the value of equipment.name
     *
     * @mbggenerated Sun Jun 06 14:27:50 CST 2021
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column equipment.name
     *
     * @param name the value for equipment.name
     *
     * @mbggenerated Sun Jun 06 14:27:50 CST 2021
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column equipment.statue
     *
     * @return the value of equipment.statue
     *
     * @mbggenerated Sun Jun 06 14:27:50 CST 2021
     */
    public String getStatue() {
        return statue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column equipment.statue
     *
     * @param statue the value for equipment.statue
     *
     * @mbggenerated Sun Jun 06 14:27:50 CST 2021
     */
    public void setStatue(String statue) {
        this.statue = statue == null ? null : statue.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column equipment.building
     *
     * @return the value of equipment.building
     *
     * @mbggenerated Sun Jun 06 14:27:50 CST 2021
     */
    public String getBuilding() {
        return building;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column equipment.building
     *
     * @param building the value for equipment.building
     *
     * @mbggenerated Sun Jun 06 14:27:50 CST 2021
     */
    public void setBuilding(String building) {
        this.building = building == null ? null : building.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column equipment.principal
     *
     * @return the value of equipment.principal
     *
     * @mbggenerated Sun Jun 06 14:27:50 CST 2021
     */
    public String getPrincipal() {
        return principal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column equipment.principal
     *
     * @param principal the value for equipment.principal
     *
     * @mbggenerated Sun Jun 06 14:27:50 CST 2021
     */
    public void setPrincipal(String principal) {
        this.principal = principal == null ? null : principal.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column equipment.remrk
     *
     * @return the value of equipment.remrk
     *
     * @mbggenerated Sun Jun 06 14:27:50 CST 2021
     */
    public String getRemrk() {
        return remrk;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column equipment.remrk
     *
     * @param remrk the value for equipment.remrk
     *
     * @mbggenerated Sun Jun 06 14:27:50 CST 2021
     */
    public void setRemrk(String remrk) {
        this.remrk = remrk == null ? null : remrk.trim();
    }
}