package com.ari.mybatis.bean;

public class Good {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column good.id
     *
     * @mbggenerated Sun Jun 06 14:27:50 CST 2021
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column good.name
     *
     * @mbggenerated Sun Jun 06 14:27:50 CST 2021
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column good.sort
     *
     * @mbggenerated Sun Jun 06 14:27:50 CST 2021
     */
    private String sort;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column good.danwei
     *
     * @mbggenerated Sun Jun 06 14:27:50 CST 2021
     */
    private String danwei;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column good.prive
     *
     * @mbggenerated Sun Jun 06 14:27:50 CST 2021
     */
    private String prive;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column good.img
     *
     * @mbggenerated Sun Jun 06 14:27:50 CST 2021
     */
    private String img;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column good.id
     *
     * @return the value of good.id
     *
     * @mbggenerated Sun Jun 06 14:27:50 CST 2021
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column good.id
     *
     * @param id the value for good.id
     *
     * @mbggenerated Sun Jun 06 14:27:50 CST 2021
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column good.name
     *
     * @return the value of good.name
     *
     * @mbggenerated Sun Jun 06 14:27:50 CST 2021
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column good.name
     *
     * @param name the value for good.name
     *
     * @mbggenerated Sun Jun 06 14:27:50 CST 2021
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column good.sort
     *
     * @return the value of good.sort
     *
     * @mbggenerated Sun Jun 06 14:27:50 CST 2021
     */
    public String getSort() {
        return sort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column good.sort
     *
     * @param sort the value for good.sort
     *
     * @mbggenerated Sun Jun 06 14:27:50 CST 2021
     */
    public void setSort(String sort) {
        this.sort = sort == null ? null : sort.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column good.danwei
     *
     * @return the value of good.danwei
     *
     * @mbggenerated Sun Jun 06 14:27:50 CST 2021
     */
    public String getDanwei() {
        return danwei;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column good.danwei
     *
     * @param danwei the value for good.danwei
     *
     * @mbggenerated Sun Jun 06 14:27:50 CST 2021
     */
    public void setDanwei(String danwei) {
        this.danwei = danwei == null ? null : danwei.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column good.prive
     *
     * @return the value of good.prive
     *
     * @mbggenerated Sun Jun 06 14:27:50 CST 2021
     */
    public String getPrive() {
        return prive;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column good.prive
     *
     * @param prive the value for good.prive
     *
     * @mbggenerated Sun Jun 06 14:27:50 CST 2021
     */
    public void setPrive(String prive) {
        this.prive = prive == null ? null : prive.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column good.img
     *
     * @return the value of good.img
     *
     * @mbggenerated Sun Jun 06 14:27:50 CST 2021
     */
    public String getImg() {
        return img;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column good.img
     *
     * @param img the value for good.img
     *
     * @mbggenerated Sun Jun 06 14:27:50 CST 2021
     */
    public void setImg(String img) {
        this.img = img == null ? null : img.trim();
    }
}