package com.ari.mybatis.bean;

public class OrderList {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orderlist.id
     *
     * @mbggenerated Sun Jun 06 14:27:50 CST 2021
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orderlist.name
     *
     * @mbggenerated Sun Jun 06 14:27:50 CST 2021
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orderlist.phone
     *
     * @mbggenerated Sun Jun 06 14:27:50 CST 2021
     */
    private String phone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orderlist.Customersource
     *
     * @mbggenerated Sun Jun 06 14:27:50 CST 2021
     */
    private String customersource;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orderlist.Customertype
     *
     * @mbggenerated Sun Jun 06 14:27:50 CST 2021
     */
    private String customertype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orderlist.Workaddress
     *
     * @mbggenerated Sun Jun 06 14:27:50 CST 2021
     */
    private String workaddress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orderlist.remarks
     *
     * @mbggenerated Sun Jun 06 14:27:50 CST 2021
     */
    private String remarks;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orderlist.Tradename
     *
     * @mbggenerated Sun Jun 06 14:27:50 CST 2021
     */
    private String tradename;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orderlist.Specifications
     *
     * @mbggenerated Sun Jun 06 14:27:50 CST 2021
     */
    private String specifications;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orderlist.Originalprice
     *
     * @mbggenerated Sun Jun 06 14:27:50 CST 2021
     */
    private String originalprice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orderlist.UnitPrice
     *
     * @mbggenerated Sun Jun 06 14:27:50 CST 2021
     */
    private String unitprice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orderlist.num
     *
     * @mbggenerated Sun Jun 06 14:27:50 CST 2021
     */
    private String num;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orderlist.subtotal
     *
     * @mbggenerated Sun Jun 06 14:27:50 CST 2021
     */
    private String subtotal;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orderlist.stock
     *
     * @mbggenerated Sun Jun 06 14:27:50 CST 2021
     */
    private String stock;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orderlist.id
     *
     * @return the value of orderlist.id
     *
     * @mbggenerated Sun Jun 06 14:27:50 CST 2021
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orderlist.id
     *
     * @param id the value for orderlist.id
     *
     * @mbggenerated Sun Jun 06 14:27:50 CST 2021
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orderlist.name
     *
     * @return the value of orderlist.name
     *
     * @mbggenerated Sun Jun 06 14:27:50 CST 2021
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orderlist.name
     *
     * @param name the value for orderlist.name
     *
     * @mbggenerated Sun Jun 06 14:27:50 CST 2021
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orderlist.phone
     *
     * @return the value of orderlist.phone
     *
     * @mbggenerated Sun Jun 06 14:27:50 CST 2021
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orderlist.phone
     *
     * @param phone the value for orderlist.phone
     *
     * @mbggenerated Sun Jun 06 14:27:50 CST 2021
     */
    public void setPhone(String phone) {
        this.phone = phone == null ? null : phone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orderlist.Customersource
     *
     * @return the value of orderlist.Customersource
     *
     * @mbggenerated Sun Jun 06 14:27:50 CST 2021
     */
    public String getCustomersource() {
        return customersource;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orderlist.Customersource
     *
     * @param customersource the value for orderlist.Customersource
     *
     * @mbggenerated Sun Jun 06 14:27:50 CST 2021
     */
    public void setCustomersource(String customersource) {
        this.customersource = customersource == null ? null : customersource.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orderlist.Customertype
     *
     * @return the value of orderlist.Customertype
     *
     * @mbggenerated Sun Jun 06 14:27:50 CST 2021
     */
    public String getCustomertype() {
        return customertype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orderlist.Customertype
     *
     * @param customertype the value for orderlist.Customertype
     *
     * @mbggenerated Sun Jun 06 14:27:50 CST 2021
     */
    public void setCustomertype(String customertype) {
        this.customertype = customertype == null ? null : customertype.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orderlist.Workaddress
     *
     * @return the value of orderlist.Workaddress
     *
     * @mbggenerated Sun Jun 06 14:27:50 CST 2021
     */
    public String getWorkaddress() {
        return workaddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orderlist.Workaddress
     *
     * @param workaddress the value for orderlist.Workaddress
     *
     * @mbggenerated Sun Jun 06 14:27:50 CST 2021
     */
    public void setWorkaddress(String workaddress) {
        this.workaddress = workaddress == null ? null : workaddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orderlist.remarks
     *
     * @return the value of orderlist.remarks
     *
     * @mbggenerated Sun Jun 06 14:27:50 CST 2021
     */
    public String getRemarks() {
        return remarks;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orderlist.remarks
     *
     * @param remarks the value for orderlist.remarks
     *
     * @mbggenerated Sun Jun 06 14:27:50 CST 2021
     */
    public void setRemarks(String remarks) {
        this.remarks = remarks == null ? null : remarks.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orderlist.Tradename
     *
     * @return the value of orderlist.Tradename
     *
     * @mbggenerated Sun Jun 06 14:27:50 CST 2021
     */
    public String getTradename() {
        return tradename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orderlist.Tradename
     *
     * @param tradename the value for orderlist.Tradename
     *
     * @mbggenerated Sun Jun 06 14:27:50 CST 2021
     */
    public void setTradename(String tradename) {
        this.tradename = tradename == null ? null : tradename.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orderlist.Specifications
     *
     * @return the value of orderlist.Specifications
     *
     * @mbggenerated Sun Jun 06 14:27:50 CST 2021
     */
    public String getSpecifications() {
        return specifications;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orderlist.Specifications
     *
     * @param specifications the value for orderlist.Specifications
     *
     * @mbggenerated Sun Jun 06 14:27:50 CST 2021
     */
    public void setSpecifications(String specifications) {
        this.specifications = specifications == null ? null : specifications.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orderlist.Originalprice
     *
     * @return the value of orderlist.Originalprice
     *
     * @mbggenerated Sun Jun 06 14:27:50 CST 2021
     */
    public String getOriginalprice() {
        return originalprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orderlist.Originalprice
     *
     * @param originalprice the value for orderlist.Originalprice
     *
     * @mbggenerated Sun Jun 06 14:27:50 CST 2021
     */
    public void setOriginalprice(String originalprice) {
        this.originalprice = originalprice == null ? null : originalprice.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orderlist.UnitPrice
     *
     * @return the value of orderlist.UnitPrice
     *
     * @mbggenerated Sun Jun 06 14:27:50 CST 2021
     */
    public String getUnitprice() {
        return unitprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orderlist.UnitPrice
     *
     * @param unitprice the value for orderlist.UnitPrice
     *
     * @mbggenerated Sun Jun 06 14:27:50 CST 2021
     */
    public void setUnitprice(String unitprice) {
        this.unitprice = unitprice == null ? null : unitprice.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orderlist.num
     *
     * @return the value of orderlist.num
     *
     * @mbggenerated Sun Jun 06 14:27:50 CST 2021
     */
    public String getNum() {
        return num;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orderlist.num
     *
     * @param num the value for orderlist.num
     *
     * @mbggenerated Sun Jun 06 14:27:50 CST 2021
     */
    public void setNum(String num) {
        this.num = num == null ? null : num.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orderlist.subtotal
     *
     * @return the value of orderlist.subtotal
     *
     * @mbggenerated Sun Jun 06 14:27:50 CST 2021
     */
    public String getSubtotal() {
        return subtotal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orderlist.subtotal
     *
     * @param subtotal the value for orderlist.subtotal
     *
     * @mbggenerated Sun Jun 06 14:27:50 CST 2021
     */
    public void setSubtotal(String subtotal) {
        this.subtotal = subtotal == null ? null : subtotal.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orderlist.stock
     *
     * @return the value of orderlist.stock
     *
     * @mbggenerated Sun Jun 06 14:27:50 CST 2021
     */
    public String getStock() {
        return stock;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orderlist.stock
     *
     * @param stock the value for orderlist.stock
     *
     * @mbggenerated Sun Jun 06 14:27:50 CST 2021
     */
    public void setStock(String stock) {
        this.stock = stock == null ? null : stock.trim();
    }
}