package com.ari.mybatis.bean;

public class Plot {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column plot.id
     *
     * @mbggenerated Sun Jun 06 14:27:50 CST 2021
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column plot.img
     *
     * @mbggenerated Sun Jun 06 14:27:50 CST 2021
     */
    private String img;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column plot.name
     *
     * @mbggenerated Sun Jun 06 14:27:50 CST 2021
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column plot.area
     *
     * @mbggenerated Sun Jun 06 14:27:50 CST 2021
     */
    private String area;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column plot.site
     *
     * @mbggenerated Sun Jun 06 14:27:50 CST 2021
     */
    private String site;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column plot.id
     *
     * @return the value of plot.id
     *
     * @mbggenerated Sun Jun 06 14:27:50 CST 2021
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column plot.id
     *
     * @param id the value for plot.id
     *
     * @mbggenerated Sun Jun 06 14:27:50 CST 2021
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column plot.img
     *
     * @return the value of plot.img
     *
     * @mbggenerated Sun Jun 06 14:27:50 CST 2021
     */
    public String getImg() {
        return img;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column plot.img
     *
     * @param img the value for plot.img
     *
     * @mbggenerated Sun Jun 06 14:27:50 CST 2021
     */
    public void setImg(String img) {
        this.img = img == null ? null : img.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column plot.name
     *
     * @return the value of plot.name
     *
     * @mbggenerated Sun Jun 06 14:27:50 CST 2021
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column plot.name
     *
     * @param name the value for plot.name
     *
     * @mbggenerated Sun Jun 06 14:27:50 CST 2021
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column plot.area
     *
     * @return the value of plot.area
     *
     * @mbggenerated Sun Jun 06 14:27:50 CST 2021
     */
    public String getArea() {
        return area;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column plot.area
     *
     * @param area the value for plot.area
     *
     * @mbggenerated Sun Jun 06 14:27:50 CST 2021
     */
    public void setArea(String area) {
        this.area = area == null ? null : area.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column plot.site
     *
     * @return the value of plot.site
     *
     * @mbggenerated Sun Jun 06 14:27:50 CST 2021
     */
    public String getSite() {
        return site;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column plot.site
     *
     * @param site the value for plot.site
     *
     * @mbggenerated Sun Jun 06 14:27:50 CST 2021
     */
    public void setSite(String site) {
        this.site = site == null ? null : site.trim();
    }
}