package com.ari.mybatis.bean;

public class wuliu {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wuliuxinxi.id
     *
     * @mbggenerated Sun Jun 06 14:27:50 CST 2021
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wuliuxinxi.receiver
     *
     * @mbggenerated Sun Jun 06 14:27:50 CST 2021
     */
    private String receiver;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wuliuxinxi.contactnumber
     *
     * @mbggenerated Sun Jun 06 14:27:50 CST 2021
     */
    private String contactnumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wuliuxinxi.Delivery_tem
     *
     * @mbggenerated Sun Jun 06 14:27:50 CST 2021
     */
    private String deliveryTem;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wuliuxinxi.deliveryweight
     *
     * @mbggenerated Sun Jun 06 14:27:50 CST 2021
     */
    private Double deliveryweight;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wuliuxinxi.receiveaddress
     *
     * @mbggenerated Sun Jun 06 14:27:50 CST 2021
     */
    private String receiveaddress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wuliuxinxi.Modeofdelivery
     *
     * @mbggenerated Sun Jun 06 14:27:50 CST 2021
     */
    private String modeofdelivery;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wuliuxinxi.remarks
     *
     * @mbggenerated Sun Jun 06 14:27:50 CST 2021
     */
    private String remarks;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wuliuxinxi.id
     *
     * @return the value of wuliuxinxi.id
     *
     * @mbggenerated Sun Jun 06 14:27:50 CST 2021
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wuliuxinxi.id
     *
     * @param id the value for wuliuxinxi.id
     *
     * @mbggenerated Sun Jun 06 14:27:50 CST 2021
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wuliuxinxi.receiver
     *
     * @return the value of wuliuxinxi.receiver
     *
     * @mbggenerated Sun Jun 06 14:27:50 CST 2021
     */
    public String getReceiver() {
        return receiver;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wuliuxinxi.receiver
     *
     * @param receiver the value for wuliuxinxi.receiver
     *
     * @mbggenerated Sun Jun 06 14:27:50 CST 2021
     */
    public void setReceiver(String receiver) {
        this.receiver = receiver == null ? null : receiver.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wuliuxinxi.contactnumber
     *
     * @return the value of wuliuxinxi.contactnumber
     *
     * @mbggenerated Sun Jun 06 14:27:50 CST 2021
     */
    public String getContactnumber() {
        return contactnumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wuliuxinxi.contactnumber
     *
     * @param contactnumber the value for wuliuxinxi.contactnumber
     *
     * @mbggenerated Sun Jun 06 14:27:50 CST 2021
     */
    public void setContactnumber(String contactnumber) {
        this.contactnumber = contactnumber == null ? null : contactnumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wuliuxinxi.Delivery_tem
     *
     * @return the value of wuliuxinxi.Delivery_tem
     *
     * @mbggenerated Sun Jun 06 14:27:50 CST 2021
     */
    public String getDeliveryTem() {
        return deliveryTem;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wuliuxinxi.Delivery_tem
     *
     * @param deliveryTem the value for wuliuxinxi.Delivery_tem
     *
     * @mbggenerated Sun Jun 06 14:27:50 CST 2021
     */
    public void setDeliveryTem(String deliveryTem) {
        this.deliveryTem = deliveryTem == null ? null : deliveryTem.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wuliuxinxi.deliveryweight
     *
     * @return the value of wuliuxinxi.deliveryweight
     *
     * @mbggenerated Sun Jun 06 14:27:50 CST 2021
     */
    public Double getDeliveryweight() {
        return deliveryweight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wuliuxinxi.deliveryweight
     *
     * @param deliveryweight the value for wuliuxinxi.deliveryweight
     *
     * @mbggenerated Sun Jun 06 14:27:50 CST 2021
     */
    public void setDeliveryweight(Double deliveryweight) {
        this.deliveryweight = deliveryweight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wuliuxinxi.receiveaddress
     *
     * @return the value of wuliuxinxi.receiveaddress
     *
     * @mbggenerated Sun Jun 06 14:27:50 CST 2021
     */
    public String getReceiveaddress() {
        return receiveaddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wuliuxinxi.receiveaddress
     *
     * @param receiveaddress the value for wuliuxinxi.receiveaddress
     *
     * @mbggenerated Sun Jun 06 14:27:50 CST 2021
     */
    public void setReceiveaddress(String receiveaddress) {
        this.receiveaddress = receiveaddress == null ? null : receiveaddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wuliuxinxi.Modeofdelivery
     *
     * @return the value of wuliuxinxi.Modeofdelivery
     *
     * @mbggenerated Sun Jun 06 14:27:50 CST 2021
     */
    public String getModeofdelivery() {
        return modeofdelivery;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wuliuxinxi.Modeofdelivery
     *
     * @param modeofdelivery the value for wuliuxinxi.Modeofdelivery
     *
     * @mbggenerated Sun Jun 06 14:27:50 CST 2021
     */
    public void setModeofdelivery(String modeofdelivery) {
        this.modeofdelivery = modeofdelivery == null ? null : modeofdelivery.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wuliuxinxi.remarks
     *
     * @return the value of wuliuxinxi.remarks
     *
     * @mbggenerated Sun Jun 06 14:27:50 CST 2021
     */
    public String getRemarks() {
        return remarks;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wuliuxinxi.remarks
     *
     * @param remarks the value for wuliuxinxi.remarks
     *
     * @mbggenerated Sun Jun 06 14:27:50 CST 2021
     */
    public void setRemarks(String remarks) {
        this.remarks = remarks == null ? null : remarks.trim();
    }
}